name: back_button_interceptor
description: Back Button Interceptor. May be used to do stuff when the Android back-button is tapped, as an alternative to `WillPopScope`.
version: 5.0.0-nullsafety.1
author: Marcelo Glasberg <marcglasberg@gmail.com>
homepage: https://github.com/marcglasberg/back_button_interceptor

environment:
  sdk: '>=2.12.0-259.9.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

